name: "test-it"
version: "2.0.0"
usage: "Test integration with Helm"
description: |-
  This plugin tests helm.
command: "$HELM_PLUGIN_DIR/bin/test-it"
hooks:
  install: "cd $HELM_PLUGIN_DIR; bash k8s/scripts/pluginctl"
  update: "cd $HELM_PLUGIN_DIR; bash k8s/scripts/pluginctl"
