#!/bin/bash

bin_name=${1:-k8s-io}
version="$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)"
os=$(uname -s)
echo "Downloading and installing ${bin_name} v${version} ..."

mkdir -p ./bin/ ./tmp/v${version}/
cd ./tmp/v${version}/

binary_file=${bin_name}-${os,,}-amd64
binary_url=https://amhub.s3.eu-central-1.amazonaws.com/distr/${bin_name}/archive/${version}/${binary_file}.tar.gz
curl -sSL ${binary_url} -o ${binary_file}.tar.gz
curl -sSL ${binary_url}.sha256sum -o ${binary_file}.tar.gz.sha256sum
sha256sum -c ${binary_file}.tar.gz.sha256sum
tar -zxC ../../bin/ -f ${binary_file}.tar.gz
mv ../../bin/${binary_file} ../../bin/${bin_name}
chmod +x ../../bin/${bin_name}
