#!/bin/bash

version="$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)"
echo "Downloading and installing v${version} ..."

mkdir -p ./bin/ ./tmp/v${version}
#bin_filename="releases/v${version}.tar.gz"
#sum_filename="releases/v${version}_checksums.txt"
#
#curl -sSL "${binary_url}" -o "${bin_filename}"
#curl -sSL "${checksum_url}" -o "${sum_filename}"
#sha256sum -c ${sum_filename}
